"""Builds the 30s soundtrack: synthesized ambient music bed + ducked voiceover.

Usage: python3 build_audio.py   (run from this directory; needs numpy + scipy)
Inputs:  vo_0.wav .. vo_5.wav   (generated by make_vo.py)
Outputs: music.wav, mix.wav (48 kHz stereo), timings.json (VO line start/end, used by index.html)
"""
import json, wave
import numpy as np
from scipy.signal import butter, sosfilt, resample_poly, fftconvolve

SR = 48000
DUR = 30.0
N = int(SR * DUR)
rng = np.random.default_rng(7)

# VO line start times (s). Scenes in index.html are keyed to these.
VO_STARTS = [0.5, 4.1, 7.9, 15.9, 20.6, 25.9]

BPM = 96
BAR = 4 * 60 / BPM            # 2.5 s
# Twelve bars, one chord per bar. Resolves V -> I on the end card.
PROG = ["D", "A", "Bm", "G", "D", "A", "Bm", "G", "Bm", "G", "A", "D"]
CHORDS = {  # MIDI notes, voiced for a warm mid register
    "D":  [50, 57, 62, 66, 69],
    "A":  [45, 57, 61, 64, 69],
    "Bm": [47, 54, 62, 66, 71],
    "G":  [43, 55, 62, 67, 71],
}
ARP = {  # upper arpeggio notes per chord
    "D":  [74, 78, 81, 86, 81, 78],
    "A":  [73, 76, 81, 85, 81, 76],
    "Bm": [74, 78, 83, 86, 83, 78],
    "G":  [74, 79, 83, 86, 83, 79],
}

t = np.arange(N) / SR
hz = lambda m: 440 * 2 ** ((m - 69) / 12)


def lp(x, fc, order=2):
    return sosfilt(butter(order, fc, "low", fs=SR, output="sos"), x)


def hp(x, fc, order=2):
    return sosfilt(butter(order, fc, "high", fs=SR, output="sos"), x)


def adsr(n, a, r):
    e = np.ones(n)
    na, nr = int(a * SR), int(r * SR)
    e[:na] = np.linspace(0, 1, na) ** 2
    e[-nr:] *= np.linspace(1, 0, nr) ** 2
    return e


def place(buf, sig, start):
    i = int(start * SR)
    j = min(len(buf), i + len(sig))
    buf[i:j] += sig[: j - i]


# ---- Pad: detuned, softly filtered chord stacks, crossfaded per bar ----
pad = np.zeros((N, 2))
for b, ch in enumerate(PROG):
    start = b * BAR - 0.4
    n = int((BAR + 1.4) * SR)
    tt = np.arange(n) / SR
    for ci, m in enumerate(CHORDS[ch]):
        for side, det in ((0, -0.07), (1, 0.07)):
            f = hz(m) * 2 ** (det / 12)
            ph = rng.uniform(0, 2 * np.pi)
            s = np.sin(2 * np.pi * f * tt + ph) + 0.35 * np.sin(4 * np.pi * f * tt + ph) + 0.12 * np.sin(6 * np.pi * f * tt)
            s *= adsr(n, 0.9, 1.2) * (0.9 if ci else 1.0)
            place(pad[:, side], s, max(0, start))
pad = np.stack([lp(pad[:, 0], 1800), lp(pad[:, 1], 1800)], 1)
pad *= (0.55 + 0.45 * np.clip(t / 3.0, 0, 1))[:, None]          # fade in from silence

# ---- Piano-ish arpeggio (8th notes) from bar 2 ----
arp = np.zeros((N, 2))
eighth = BAR / 8
for b, ch in enumerate(PROG):
    if b < 1:
        continue
    for k in range(8):
        m = ARP[ch][k % 6]
        st = b * BAR + k * eighth
        n = int(1.6 * SR)
        tt = np.arange(n) / SR
        f = hz(m)
        s = (np.sin(2 * np.pi * f * tt) + 0.4 * np.sin(4 * np.pi * f * tt) * np.exp(-tt * 6)
             + 0.15 * np.sin(6 * np.pi * f * tt) * np.exp(-tt * 9))
        s *= np.exp(-tt * 3.2) * np.minimum(1, tt / 0.004)
        vel = 0.55 + 0.25 * (k % 2 == 0) + (0.15 if b >= 6 else 0)
        pan = 0.5 + 0.3 * np.sin(k * 1.3)
        place(arp[:, 0], s * vel * (1 - pan), st); place(arp[:, 1], s * vel * pan, st)

# ---- Sub bass on chord roots from bar 3 ----
bass = np.zeros(N)
for b, ch in enumerate(PROG):
    if b < 3:
        continue
    root = CHORDS[ch][0] - 12
    n = int(BAR * SR) + int(0.3 * SR)
    tt = np.arange(n) / SR
    s = np.sin(2 * np.pi * hz(root) * tt) * adsr(n, 0.08, 0.5)
    place(bass, s, b * BAR)
bass = lp(bass, 220)

# ---- Soft pulse (kick + shaker) for the lift, bars 6-11 ----
perc = np.zeros(N)
beat = 60 / BPM
for i in range(int(DUR / beat)):
    st = i * beat
    if st < 6 * BAR or st > 11 * BAR + 0.1:
        continue
    n = int(0.35 * SR); tt = np.arange(n) / SR
    kick = np.sin(2 * np.pi * (48 + 60 * np.exp(-tt * 30)) * tt) * np.exp(-tt * 9)
    place(perc, kick * 0.9, st)
    for h in (0, 0.5):
        n2 = int(0.09 * SR)
        sh = hp(rng.standard_normal(n2), 6000) * np.exp(-np.arange(n2) / SR * 45)
        place(perc, sh * (0.12 if h else 0.07), st + h * beat)
perc_st = np.stack([perc, perc], 1)

# ---- Riser + shimmer into the end card ----
rise_n = int(2.2 * SR)
riser = hp(rng.standard_normal(rise_n), 3000) * np.linspace(0, 1, rise_n) ** 3 * 0.18
riser_buf = np.zeros(N); place(riser_buf, riser, 25.5 - 2.2)
riser_st = np.stack([riser_buf, riser_buf], 1)

# ---- Reverb (synthetic stereo IR) ----
def reverb(x, secs=2.8, mix=0.35):
    n = int(secs * SR)
    decay = np.exp(-np.arange(n) / SR * (6.9 / secs))
    out = np.zeros_like(x)
    for c in range(2):
        ir = lp(rng.standard_normal(n), 5000) * decay
        ir /= np.sqrt((ir ** 2).sum())
        out[:, c] = fftconvolve(x[:, c], ir)[: len(x)]
    return (1 - mix) * x + mix * out

music = (0.30 * pad + 0.22 * arp + 0.35 * np.stack([bass, bass], 1) + 0.25 * perc_st + riser_st)
music = reverb(music, 3.2, 0.4)
# Final ring-out: fade the last 1.2 s
fade = np.ones(N); fn = int(1.2 * SR); fade[-fn:] = np.linspace(1, 0, fn) ** 1.5
music *= fade[:, None]
music /= np.abs(music).max() + 1e-9

# ---- Voiceover: resample, clean, compress, place ----
vo = np.zeros(N)
timings = []
for i, st in enumerate(VO_STARTS):
    w = wave.open(f"vo_{i}.wav")
    a = np.frombuffer(w.readframes(w.getnframes()), np.int16).astype(float) / 32768
    a = resample_poly(a, SR, w.getframerate())
    a = hp(a, 90)
    a /= np.abs(a).max() + 1e-9
    place(vo, a, st)
    timings.append([st, round(st + len(a) / SR, 2)])

def compress(x, thr=0.35, ratio=3.0, att=0.005, rel=0.12):
    env = np.zeros_like(x); e = 0.0
    ca, cr = np.exp(-1 / (att * SR)), np.exp(-1 / (rel * SR))
    ax = np.abs(x)
    for i in range(len(x)):
        c = ca if ax[i] > e else cr
        e = c * e + (1 - c) * ax[i]
        env[i] = e
    gain = np.where(env > thr, (thr + (env - thr) / ratio) / np.maximum(env, 1e-9), 1.0)
    return x * gain

vo = compress(vo)
vo /= np.abs(vo).max() + 1e-9
vo_rev = reverb(np.stack([vo, vo], 1), 0.9, 0.08)

# ---- Duck music under VO ----
env = lp(np.abs(vo), 6)
env /= env.max() + 1e-9
duck = 1 - 0.45 * np.clip(env * 4, 0, 1)
duck = lp(duck, 3)
# Let the music swell a little on the end-card tag.
swell = 1 + 0.25 * np.clip((t - 25.5) / 1.5, 0, 1)

mix = 0.80 * vo_rev + 0.30 * music * (duck * swell)[:, None]
mix /= np.abs(mix).max() / 0.89       # peak about -1 dBFS

def write(path, x):
    x16 = (np.clip(x, -1, 1) * 32767).astype(np.int16)
    with wave.open(path, "wb") as w:
        w.setnchannels(2); w.setsampwidth(2); w.setframerate(SR)
        w.writeframes(x16.tobytes())

write("music.wav", music * 0.7)
write("mix.wav", mix)
json.dump(timings, open("timings.json", "w"))
print("VO timings:", timings)
